---
- name: Install OpenSlides dependencies
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - redis-server
  - python-psycopg2  # Needed for ansible
  - python3-psycopg2  # Needed for OpenSlides
  - postgresql
  - postgresql-client
  - python3-pip

- name: Configure postgresql
  become: yes
  lineinfile:
    dest: /etc/postgresql/9.4/main/pg_hba.conf
    state: present
    line: host all all 127.0.0.1/32 trust

- name: Set postgres password
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: postgres

- name: Install nginx
  when: openslides_nginx_domains or openslides_nginx_global
  become: yes
  apt:
    name: nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

# Needed for html5lib. Can be removed soon
- name: Install newser setuptools version
  become: yes
  pip:
    name: setuptools
    executable: "pip3"
    version: 27

- name: Add source for newer node source
  when: openslides_use_git
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

- name: Install git and development tools
  when: openslides_use_git
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - git
  - nodejs

- name: Set locale
  become: yes
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Create a symlink from nodejs to node
  when: openslides_use_git
  become: yes
  file:
    state: link
    path: /usr/bin/node
    src: /usr/bin/nodejs

- set_fact:
    pip_executable: pip3
    openslides_distro_fround: true
    openslides_bin: /usr/local/bin/openslides
    daphne_bin: /usr/local/bin/daphne
    redis_service: redis-server
    postgres_connection: host
